#+TITLE:     Emacs Chat avec Sacha Chua
#+AUTHOR:    Fabrice Niessen
#+DATE:      2026-08-13
#+LANGUAGE:  fr
#+OPTIONS:   toc:2 num:2

#+SETUPFILE: ~/org/setup/org-macros.setup

# HTML export.
#+SETUPFILE: ~/org/setup/html-theme-readtheorg.setup

# LaTeX export.
#+LATEX_CLASS: mcreport
#+SETUPFILE: ~/org/setup/latex-listings.setup
#+SETUPFILE: ~/org/setup/latex-fonts.setup
#+SETUPFILE: ~/org/setup/latex-admonitions.setup
#+LATEX_HEADER: % * Document Setup

* Présentation

Je suis consultant IT en Belgique (à Leuven ;-)) et utilisateur passionné
d'Emacs depuis 1999.

Au fil des années, j'ai développé plusieurs projets /open source/ autour d'Emacs
et d'Org mode, principalement pour :

- la personnalisation d'Emacs ;
- l'automatisation des tâches répétitives (DRY) ;
- la rédaction et la publication de documents techniques (vers HTML, LaTeX et
  PDF) à partir d'une source unique (macros Org) ;
- la diffusion d'Org mode à travers des /refcards/ sur la syntaxe Org mode et sur
  Org Babel (/literate programming/, /reproducible research/).

#+begin_tip
Aujourd'hui, la plupart de mes outils et expérimentations sont publiés sur
GitHub et servent également de support à mes formations EmacsBoost (et
ShellBoost... et GitBoost...).
#+end_tip

Référence : https://github.com/fniessen

* Agenda

Quelques sujets que l'on pourrait aborder :

- mon parcours avec Emacs ;
- le thème (officiel) de couleurs [[*leuven-theme][Leuven]] ;
- ma configuration Emacs ("[[*Emacs Leuven (EmacsBoost)][Emacs Leuven]]") ;
- [[*Export vers HTML][org-html-themes]] ;
- [[*Export vers PDF][boost-org-latex-toolkit]] ;
- [[*Mon organisation quotidienne][mon organisation quotidienne]] ;
- [[*Quelques astuces][quelques astuces]] et automatisations ;
- les [[*Formations EmacsBoost][formations EmacsBoost]].

Tous ces projets répondent à des besoins rencontrés dans mon travail quotidien.

* leuven-theme

Le thème =leuven= est un thème clair qui privilégie :

- la lisibilité ;
- un contraste suffisant ;
- des couleurs peu fatigantes ;
- une hiérarchie visuelle claire.

Je l'ai conçu pour pouvoir travailler plusieurs heures par jour sans fatigue
visuelle.

Référence : https://github.com/fniessen/emacs-leuven-theme

* Emacs Leuven (EmacsBoost)

Ma configuration =emacs-leuven= est l'aboutissement de nombreuses années
d'utilisation quotidienne.

L'objectif n'est pas de montrer "la meilleure configuration Emacs", mais une
configuration "Emacs pour humains habitués aux IDE modernes" :

- cohérente ;
- documentée ;
- facile à comprendre ;
- composée de plein de petites améliorations qui, mises bout à bout, changent
  vraiment l'expérience utilisateur -- et rendent Emacs tout simplement
  indispensable.

C'est aussi un excellent support pédagogique pour découvrir de nombreuses
fonctionnalités d'Emacs.

#+begin_note
Depuis quelque temps, je suis progressivement en train de faire évoluer ce
projet sous le nom *EmacsBoost*. Ce nouveau nom reflète mieux son ambition :
proposer non seulement une configuration Emacs prête à l'emploi, mais également
un ensemble cohérent de configurations, d'automatisations et d'outils pour aider
chacun à tirer le meilleur parti d'Emacs.
#+end_note

Référence : https://github.com/fniessen/emacs-leuven

* Export vers HTML

=org-html-themes= est né d'un besoin très concret : *produire facilement des
exports* HTML Org mode qui soient directement publiables, professionnels et
agréables à lire.

Le projet fournit plusieurs thèmes complets (dont *ReadTheOrg* et *Bigblow*)
ainsi que toute l'infrastructure nécessaire pour transformer un simple document
Org en une documentation moderne.

Objectifs :

- zéro CSS à écrire ;
- une navigation confortable ;
- une excellente lisibilité ;
- un rendu professionnel ;
- une personnalisation simple.

Référence : https://github.com/fniessen/org-html-themes

* Export vers PDF

Références :
- https://github.com/fniessen/boost-org-latex-toolkit
- https://github.com/fniessen/org-macros

* Mon organisation quotidienne

** TODO Org mode                                                      :personal:

Org mode est le centre de mon organisation.

Je l'utilise pour :

- gérer mes tâches ;
- prendre des notes ;
- préparer mes (supports de) formations ;
- écrire de la documentation ;
- suivre mes projets personnels.

** STRT Suivi du temps passé                                              :work:

Je mesure précisément le temps consacré à mes activités professionnelles grâce
au système de =org-clock-in= / =org-clock-out=.

Cela me permet :

- de retrouver facilement ce que j'ai fait ;
- de produire des factures.

* Quelques astuces

Quelques petites choses qui font *gagner beaucoup de temps*.

** C-w / M-w sans sélectionner de région

Couper ou copier la ligne courante lorsqu'aucune région n'est active.

Référence :
https://github.com/fniessen/emacs-leuven/blob/master/docs/emacs-leuven.txt#deletion-and-killing

** VCS (Git)

*** EDiff

| Touche | Commande |
|--------+----------|
| ~E~      | ~vc-ediff~ |

Référence :
https://github.com/fniessen/emacs-leuven/blob/master/docs/emacs-leuven.txt#vc-directory-mode

*** Messages de commit

Génération automatique de messages de commit par IA.

Référence :
https://github.com/fniessen/emacs-leuven/blob/master/docs/emacs-leuven-ai.txt#git-commit-messages

** Mise à jour automatique du contenu avant enregistrement

La fonction =boost--org-update-generated-content-before-save= met automatiquement
à jour certaines parties du document juste avant l'enregistrement : elle
recalcule les blocs dynamiques et les tables, et réaligne les tags.

Cela évite les oublis et garantit que
{{{hl(les données dérivées restent synchronisées avec leur source)}}}. \\
/Hey user, this is an *Org macro*.../

{{{clearpage}}}

Lignes de facturation :

#+name: participants
#+ATTR_HTML: :style margin-left:auto; margin-right:auto;
| Nom           | Société | Prix HT |   |
|---------------+---------+---------+---|
| Alice Martin  | ACME    |  500.00 | \EUR |
| Bob Dupont    | ACME    |  500.00 | \EUR |
| Claire Durand | Contoso |  750.00 | \EUR |
| David Leroy   | ACME    |  500.00 | \EUR |
|---------------+---------+---------+---|
| Total         |         | 2250.00 | \EUR |
#+TBLFM: @6$3=vsum(@I..@-I);%.2f

Montant à facturer :

#+LATEX: \hfill\colorbox{black!10}{\begin{minipage}{7.5cm}
#+ATTR_HTML: :style margin-left:auto; margin-right:0;
#+ATTR_LATEX: :environment tabu :align Xrl
| /Sous-total HT/ | 2250.00 | \EUR |
| /TVA @ 21%/     |  472.50 | \EUR |
|---------------+---------+---|
| *Total TTC*     | *2722.50* | *\EUR* |
#+TBLFM: @1$2=remote(participants,@>$3);%.2f::@2$2=@1*0.21;%.2f::@3$2=vsum(@1..@-1);*%.2f*
#+LATEX: \end{minipage}}

Référence :
https://github.com/fniessen/emacs-leuven/blob/master/docs/emacs-leuven-org.txt#a6-dynamic-blocks

** Édition rectangle

L'édition rectangle est l'une de ces fonctionnalités méconnues d'Emacs qui
deviennent rapidement indispensables dès que l'on manipule du texte
semi-structuré -- elle fait gagner énormément de temps.

Elle permet de sélectionner et de modifier (couper, copier, effacer ou
remplacer) une zone *rectangulaire* de texte.

J'utilise cette fonctionnalité régulièrement pour :

- insérer ou supprimer un préfixe sur plusieurs lignes ;
- transformer rapidement des listes ;
- préparer des données ;
- éditer des blocs de code ou des fichiers de configuration.

Par exemple :

#+begin_example
Alice    Martin    Bruxelles
Bob      Dupont    Namur
Claire   Durand    Liège
#+end_example

** Automatisations dans Dired

Quelques exemples :

| Touche  | Commande                                 |
|---------+------------------------------------------|
| ~C-x C-j~ | ~dired-jump~ (global)                      |
| ~o~       | ~boost-dired-open-marked-files-externally~ |

** Automatisations dans Isearch

| Touche | Commande                |
|--------+-------------------------|
| ~C-o~    | ~helm-swoop-from-isearch~ |

Nombre de correspondances grâce à Anzu.

** Autres raccourcis de productivité

Les touches de fonction ci-dessous offrent un mode de travail inspiré de Borland
Pascal pour les opérations les plus courantes : gestion des fichiers, navigation
entre fenêtres et buffers, vues d'agenda Org, macros clavier, gestion de
versions et navigation dans les erreurs de compilation.

| Touche  | Commande                           |
|---------+------------------------------------|
| ~<f2>~    | ~save-buffer~                        |
| ~<f3>~    | ~find-file~ / ~helm-for-files~         |
|---------+------------------------------------|
| ~<f5>~    | ~boost-toggle-window-split~          |
| ~<f6>~    | ~boost-previous-buffer-or-window~    |
|---------+------------------------------------|
| ~<f8>~    | ~call-last-kbd-macro~                |
| ~S-<f8>~  | ~boost-toggle-kmacro-recording~      |
| ~C-<f8>~  | ~kmacro-name-last-macro~             |
|---------+------------------------------------|
| ~<f9>~    | ~boost--org-rebuild-dependent-files~ |
| ~C-<f9>~  | ~boost-vc-status-here~               |
|---------+------------------------------------|
| ~<f10>~   | ~next-error~                         |
| ~S-<f10>~ | ~previous-error~                     |
| ~C-<f10>~ | ~first-error~                        |
|---------+------------------------------------|
| ~<f11>~   | ~undo-only~                          |
| ~S-<f11>~ | ~undo-redo~                          |
|---------+------------------------------------|
| ~<f12>~   | ~switch-to-buffer~  / ~helm-mini~      |
| ~S-<f12>~ | ~boost-kill-current-buffer~          |
| ~C-<f12>~ | ~boost-helm-generic-imenu~           |
| ~M-<f12>~ | ~bury-buffer~                        |
|---------+------------------------------------|
| ~C-c 1~   | ~find-name-dired~                    |
| ~C-c 2~   | ~find-grep-dired~                    |
| ~C-c 3~   | ~rgrep~                              |
|---------+------------------------------------|
| ~M-q~     | ~boost-fill-paragraph-dwim~          |
|---------+------------------------------------|
| ~M-S-a~   | ~boost-show-hidden-text~             |

Les variantes de =F6= permettent notamment d'afficher des vues d'agenda adaptées
au contexte courant, depuis le fichier actif jusqu'à l'ensemble du projet.

| Touche   | Commande                             |
|----------+--------------------------------------|
| ~S-<f6>~   | ~boost-org-agenda-current-file~        |
| ~C-<f6>~   | ~boost-org-agenda-project-org~         |
| ~M-<f6>~   | ~boost-org-agenda-project-org-and-txt~ |
| ~M-S-<f6>~ | ~boost-project-unscheduled-todos~      |

** Intégration avec le Shell

Quelques commandes permettent d'établir un pont pratique entre Emacs et le
terminal.

- ~e~ pour ouvrir un fichier (ou un répertoire) dans l'instance Emacs en cours
  à l'aide de =emacsclient= :

  #+begin_src shell
  alias e='emacsclient -n -a emacs'
  #+end_src

- ~cate~ pour afficher dans le terminal le contenu du buffer actuellement actif
  dans Emacs.

- ~cde~ pour se placer dans le répertoire du fichier actuellement ouvert dans
  Emacs.

Référence :
https://github.com/fniessen/emacs-leuven/blob/master/docs/emacs-leuven.txt#shell-utilities

* Formations EmacsBoost

L'objectif de mes formations est simple : transmettre toutes les fonctionnalités
d'Emacs que j'utilise au quotidien, et qui me font réellement gagner du temps.

Les formations mettent l'accent sur :

- les raccourcis utiles ;
- Org mode ;
- la gestion des projets ;
- les automatisations ;
- la personnalisation ;
- les bonnes pratiques.

L'objectif est que les participants puissent appliquer immédiatement ce qu'ils
ont appris dès leur retour au travail.

Prochaine date à Paris : (Q4 2026 ou) Q1 2027.

Référence : https://emacsboost.com

** Témoignages

Quelques retours récurrents des participants :

- "J'ai découvert énormément de fonctionnalités que je n'aurais jamais trouvées
  seul."
- "Le gain de productivité est immédiat."
- "La formation est très concrète."
- "Même après 20 ans d'utilisation quotidienne d'Emacs, j'ai appris énormément."

* Merci

Merci pour ton intérêt !

J'espère que cette conversation aura été une bonne occasion d'échanger quelques
idées, expériences et astuces autour d'Emacs, d'Org mode et de l'/open source/.
